import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from '@/components/AuthProvider';
import { ConditionalNavbar } from '@/components/ConditionalNavbar';
import { CartProvider } from '@/context/CartContext';
import { Toaster } from 'react-hot-toast';
import { ConditionalFooter } from '@/components/ConditionalFooter';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-app min-h-screen`}
      >
        <AuthProvider>
          <CartProvider>
            <Toaster />
            <ConditionalNavbar />
            {children}
            <ConditionalFooter />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
